name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start quorum with '...'
        2. Select models '...'
        3. Ask question '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: If applicable, paste any error messages or logs.
      render: shell

  - type: input
    id: version
    attributes:
      label: Quorum version
      description: Run `quorum --version` or check pyproject.toml
      placeholder: "0.1.0"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows (WSL)
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
